### ISSUE TITLE
[BUG] Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by erickcouto** [Dabolus/google-assistant-desktop-unofficial#2]
**Describe the bug**
Im getting this error when I put the client ID and secret

Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:45515, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials.....

**Comment by Dabolus** [comment]
Sorry for the late response, I was on holiday. Tomorrow I will check out what the problem might be, but I'm quite sure it is that I forgot to write a step in the initial tutorial (I never had the chance to test an entire tutorial flow since the start of the project). Thanks for reporting it!

**Comment by Dabolus** [comment]
Ok I added the missing step to the wizard and I was now able to test a complete tutorial flow without particular issues, so the missing step was most probably the reason why you weren't able to configure the Assistant correctly. I consider this bug solved, but feel free to open it again if the issue persists for you.
